### ISSUE TITLE
can't start monailabel server using `-a api`

### ISSUE THREAD

**Issue by hw-ju** [nadeemlab/ImPartial#14]
Hi!
After I run:
```
cd impartial
monailabel start_server -a api -s ~/ImPartial/Data/Vectra_WC_2CH_tiff/
```
I get error:
```
[2022-11-22 09:48:21,068] [1509998] [MainThread] [INFO] (uvicorn.error:75) - Started server process [1509998]
[2022-11-22 09:48:21,068] [1509998] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2022-11-22 09:48:21,069] [1509998] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: /home/hju/ImPartial/impartial/api; studies: /home/hju/ImPartial/Data/Vectra_WC_2CH_tiff; conf: {}
[2022-11-22 09:48:21,092] [1509998] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.Impartial'>
[2022-11-22 09:48:21,105] [1509998] [MainThread] [ERROR] (uvicorn.error:119) - Traceback (most recent call last):
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/site-packages/monailabel/app.py", line 104, in startup_event
    instance = app_instance()
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 51, in app_instance
    app = c(app_dir=app_dir, studies=studies, conf=conf)
  File "/home/hju/ImPartial/impartial/api/main.py", line 25, in __init__
    for c in get_class_names(lib.configs, "TaskConfig"):
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/site-packages/monailabel/utils/others/class_utils.py", line 144, in get_class_names
    module = importlib.import_module("." + name, package=current_module_name)
  File "/home/hju/anaconda3/envs/monailabel-impartial-env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hju/ImPartial/impartial/api/lib/configs/impartial.py", line 5, in <module>
    import lib.infers
  File "/home/hju/ImPartial/impartial/api/lib/infers/__init__.py", line 1, in <module>
    from .impartial import Impartial
  File "/home/hju/ImPartial/impartial/api/lib/infers/impartial.py", line 25, in <module>
    from monailabel.interfaces.tasks.infer_v2 import InferType
ModuleNotFoundError: No module named 'monailabel.interfaces.tasks.infer_v2'
```
I `pip` installed monailabel and other packages in `requirements.txt` within a conda environment, as when I tried to follow the python virtual environment setup   in the readme https://github.com/nadeemlab/ImPartial#monai-label, openslide-python can't be installed. And according to  https://openslide.org/api/python/#installing , it seems to better install openslide using some package manger like Anaconda.

I've done some testing on the monailabel installation. E.g., I can start a monailabel server if using a monailabel sample pathology application:
```
monailabel start_server -a apps/pathology/ -s ~/ImPartial/Data/Vectra_WC_2CH_tiff/
```
Also, using monailabel radiology sample application together with 3DSlicer also works. Any ideas?

**Comment by gunjan-sh** [comment]
Hi, 

We have made several updates. Please take the latest main branch.
